---
title: "S1: Métodos númericos para la solución de Sistemas de EDOS"
weight: 1
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
subtitle: ''
slug: "2022AD-MA1002-blog1"
draft: no
excerpt: Presentación de los métodos númericos de Euler, Euler modificado y Runge-Kutta para la solución de Euler en el lenguaje de R.
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.show =('asis'),
  dev='png',
	message = FALSE,
	warning = FALSE,
	cache = FALSE,
	hiline = TRUE,
	out.width = "90%"
)
```


# Método de Euler

La siguiente rutina sirve para aplicar el método de Euler para aproximar la solución de un sistema de EDOs.

Recordemos que nosotros que nuestro problema de la vida real se modela con un sistema de ecuaciones de la forma: $$\begin{array}{ccc} x'(t) & = & f_1(t,x(t),y(t)) \\ y'(t) & = & f_2(t,x(t),y(t)) \end{array} $$ con valores iniciales $x(0)=x_0$ y $y(0)=y_0.$

_Nota:_ Cabe mencionar que podemos tener más de dos ecuaciones con más funciones incógnita.

## La idea del método:

Recordemos que el método de Euler se basa en la aproximación de una función mediante el _polinomio de Taylor_ de orden 1, es decir, $$f(t+h)=f(t)+hf'(t) + E(t,h)$$ donde $E(t,h)$ es un error. Debido a que sabemos que nuestra función deseada satisface la ecuación diferencial $$ x'(t) =  f_1(t,x(t),y(t))$$ podemos sustituir esto en la fórmula del polinomio de Taylor y obtener una aproximación a través de la función multivaluada $f_1(t,x,y).$

Así, lo anterior, implica que si queremos conocer el valor de la solución cerca de nuestras condiciones iniciales, podemos utilizar la expresión: $$x(t+h)=x(t)+hf_1(t,x(t),y(t)).$$
$$y(t+h)=y(t)+hf_2(t,x(t),y(t)).$$